---
- name: Create pods using deployment
  hosts: kube
  become: true
  user: root

  tasks:
  - name: create a deployment
    command: kubectl apply -f https://github.com/meghanabotcha/DevOps_ClassNotes/blob/master/CICD%20pipeline/kubedeployment.yml
